# Generated by Django 5.1.3 on 2026-01-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['order']},
        ),
    ]
