# Generated by Django 5.1.3 on 2026-01-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_dailyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=20),
        ),
    ]
